#!/bin/bash
# Tested on Mac OS X
#
# To run:
#   cd junit
#   ./runtests
#
# Read JUNIT.en.md for instructions
# This script works with tests in junit directory
# For other platforms please ask for help during asg session
(cd .. && javac *.java) && \
javac -encoding UTF-8 -cp junit-4.13.jar:hamcrest-core-1.3.jar:.:.. *.java && \
 java -cp junit-4.13.jar:hamcrest-core-1.3.jar:.:.. TestA04
  